### PR TITLE
Fix v1.7.1 issues

### PR DESCRIPTION
**Pull request by ChenYingChou**
After installing v1.7.1 with `npm i -g markserv`, there are some issues:
1. Missing CSS files in directory `lib/templates`.
1. The request `{Markserv}templates/markserv.css` always returns 404, but changing the code in `server.js` to `const markservUrlLead = '{markserv}'` yields the correct content.

Improve these:
1. Change emoji characters to shortcuts: Affect the heading anchors.
1. Add emoji-regex and markdown-it-emoji modules: This will generate the same heading anchors as github.
1. Add function `ahref()`: Generate more secure links.
1. Return a more secure page when a request error occurs. 
1. Disable dot-files in dir listing. Maybe we can add a command parameter to toggle it.
1. If the `livereloadport` is zero, the `liveReload` is completely disabled.
1. Delete the file `github.less`, which is almost the same as `markserv.css`.
1. Remove unused `prettyPath` variable from `dirToHtml()`.
1. Change to Responsive Web Design, better for mobile browsing.
1. Update the URL of `MathJax.js`, the original cdn url warns:\
WARNING: cdn.mathjax.org has been retired. Check https://www.mathjax.org/cdn-shutting-down/ for migration tips.
1. I changed your `crumbs` code and my code in html is a bit ugly.

### CODE REVIEW

**Comment by ChenYingChou** [comment]
The secure link means the user enters the url `http://example.com/<script>alert('test')</script>`,
markserv should return 404 raw data:
```
404 :'( for Error: ENOENT: no such file or directory, stat '/homedir/&lt;script&gt;alert('test')&lt;/script&gt;'
```
but not:
```
404 :'( for Error: ENOENT: no such file or directory, stat '/homedir/<script>alert('test')</script>
```

Chrome will block this returned page, but Firefox will execute the script.

Similarly, when generating a directory listing, be careful with `URL` and `FILE NAME` in `<a href="URL">FILE NAME</a>`.

**Comment by F1LT3R** [comment]
Will get to this when I can. Thank you!

**Comment by F1LT3R** [comment]
I'm looking at how you updated the URLs:

- Before: `/markserv}templates/markserv.css`
- After: `/{markserv}/templates/markserv.css`

This causes a 404 for me on macOS Chrome.

screen shot 2018-05-05 at 3 48 48 pm

When I echo out the markservUrl...

```js
// lib/server.js:373
		const isMarkservUrl = req.url.includes(markservUrlLead)

		// Double check the url in the request Handler
		console.log(isMarkservUrl, req.url)

		if (isMarkservUrl) {
			const markservFilePath = req.url.split(markservUrlLead)[1]
			const markservRelFilePath = path.join(__dirname, markservFilePath)
			if (flags.verbose) {
				msg('{markserv url}', style.link(markservRelFilePath), flags)
			}
			send(req, markservRelFilePath, {
				immutable: true,
				maxAge: '1d'
			}).pipe(res)
			return
		}
```

I get this:

screen shot 2018-05-05 at 3 56 31 pm

Perhaps your browser/os acts differently when it provides the path?

What do you see when you `console.log(isMarkservUrl, req.url)` ?

**Comment by F1LT3R** [comment]
What Browser and OS are you using @ChenYingChou ?

**Comment by F1LT3R** [comment]
I'm wondering if you changed `markservUrlLead` because it was easier to read? Or because things would not work without the change?

**Comment by F1LT3R** [comment]
I'm sorry @ChenYingChou, accidental merge. Can you push to this branch again to re-open?

**Comment by ChenYingChou** [comment]
Here is my server: https://md.tvmall.com.tw/

```
tony@dev:~/markdown> cat /etc/centos-release
CentOS Linux release 7.4.1708 (Core)

tony@dev:~/markdown> ls -lF
total 0
lrwxrwxrwx 1 tony tony 11 May  5 18:21 markserv -> ../markserv/
drwxrwxr-x 5 tony tony 61 Apr 29 01:16 oisp/
drwxrwxr-x 5 tony tony 43 May  8 02:37 <sub>T & 中文<%2Fsub>/

tony@dev:~/markdown> node ~/markserv/lib/cli.js -p 8002 -l 0
  Markserv   address: http://localhost:8002
  Markserv   path: /home/tony/markdown
  Markserv   process: your pid is: 4928
  Markserv   stop: press [Ctrl + C] or type "sudo kill -9 4928"
   GitHub   Contribute on Github - github.com/f1lt3r/markserv
 ▕● PATREON  Help support Markserv - Become a Patreon! patreon.com/f1lt3r
```

I run nginx with reverse-proxy:

```config
# Markdown Server
server {
    server_name  md.tvmall.com.tw;
    include ssl.conf;
    location / {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Host $host;
        proxy_pass http://127.0.0.1:8002/;
    }
}
```

**Comment by ChenYingChou** [comment]
> I'm wondering if you changed markservUrlLead because it was easier to read? Or because things would not work without the change?

I found that the URL through the nginx reverse proxy will be decoded, so `%7Bmarkserv%7D` is changed to `{markserve}`.

If you directly request to `http://ip:port/{markserv}`, the URL is still "%7Bmarkserv%7D".

Make the following changes to handle both situations correctly:
```diff
@@ -370,9 +370,10 @@ const createRequestHandler = flags => {
                        msg('request', filePath, flags)
                }

-               const isMarkservUrl = req.url.includes(markservUrlLead)
+               const decodedReqUrl = unescape(req.url)
+               const isMarkservUrl = decodedReqUrl.includes(markservUrlLead)
                if (isMarkservUrl) {
-                       const markservFilePath = req.url.split(markservUrlLead)[1]
+                       const markservFilePath = decodedReqUrl.split(markservUrlLead)[1]
                        const markservRelFilePath = path.join(__dirname, markservFilePath)
                        if (flags.verbose) {
                                msg('{markserv url}', style.link(markservRelFilePath), flags)
```
In my version: `const markservUrlLead = '/{markserv}/'`
I also changed `lib/templates/*.html`

**Comment by ChenYingChou** [comment]
> Can you push to this branch again to re-open?

Should I make a new PR?

**Comment by F1LT3R** [comment]
Ideally we should have a PR for each feature you're adding/updating. But I'm ok with a single new PR if that's all you have time for.

**Comment by F1LT3R** [comment]
@ChenYingChou now I see how you are using the internal `{markserv}` url through a proxy, we might do better to use safe url characters only. 

Perhaps something like `__markserv__` or  `.markserv` to denote the `./lib` directory is better? (It probably doesn't matter what it looks like as this will be internal facing.)

**Pull request merged**
