### PR TITLE
Fix encoded URL will return 404

### PR DESCRIPTION
**Pull request by imyzf**
if a URL contains Chinese like `测试.md`, it will be encoded by Chrome to `%E6%B5%8B%E8%AF%95.md`.

### CODE REVIEW

**Comment by F1LT3R** [comment]
That's great thanks, @imyzf. Can you add a test document to the `./examples` directory?

**Comment by imyzf** [comment]
OK, I have added a `测试.md` to the `./examples` directory, although it looks strangely with other English filename. 😂

**Comment by F1LT3R** [comment]
I will try and get to this soon.

Just out of interest: does "测试" mean "README"?

**Review by F1LT3R — APPROVED** [review]
Thanks for this fix!

**Comment by F1LT3R** [comment]
Seems good now.

screen shot 2018-04-19 at 2 07 37 pm

Could you `npm i -g markserv` and check that things work as you would expected.

This work is also referred to here: https://github.com/F1LT3R/markserv/issues/17

Can we close this?

**Comment by imyzf** [comment]
I have installed new version and it works. And "测试" means "test" in Chinese.😄

**Pull request merged**
