### PR TITLE
Improve some features

### PR DESCRIPTION
**Pull request by ChenYingChou**
1. Change emoji characters to shortcuts: Affect the heading anchors.
1. Add emoji-regex and markdown-it-emoji modules: This will generate the same heading anchors as github.
1. Add function `ahref()`: Generate more secure links.
1. Return a more secure page when a request error occurs.
1. Disable dot-files in dir listing. Maybe we can add a command parameter to toggle it.
1. If the `livereloadport` is zero, the `liveReload` is completely disabled.
1. Delete the file `github.less`, which is almost the same as `markserv.css`.
1. Remove unused `prettyPath` variable from `dirToHtml()`.
1. Change to Responsive Web Design, better for mobile browsing.
1. Update the URL of `MathJax.js`, the original cdn url warns:\
WARNING: cdn.mathjax.org has been retired. Check https://www.mathjax.org/cdn-shutting-down/ for migration tips.
1. I changed your `crumbs` code and my code in html is a bit ugly.

Sorry, I can't find how to submit a PR for each future.

### CODE REVIEW

**Comment by ChenYingChou** [comment]
Should I destroy my repository and then fork again from the last repository and apply each feature step by step?

**Comment by ChenYingChou** [comment]
Should I destroy my repository and then fork again from the last repository and apply each feature step by step?

**Comment by F1LT3R** [comment]
That would definitely make it much easier for me to consume! Apologies on the lateness, it has been a very busy week so I have not had the time to dig into your code yet.

**Comment by F1LT3R** [comment]
I've started working on some of these changes manually:

- README Emoji Fix - https://github.com/F1LT3R/markserv/pull/49
- Emoji Markdown Support - https://github.com/F1LT3R/markserv/pull/50

I'm just attempting to split the functionality of your work into separate PRs.

The items planed for release this week (based off your PR #48) are:

1. ~~Slugify Links~~ [PR 51](https://github.com/F1LT3R/markserv/pull/51)
1. ~~Update Breadcrumbs~~ [PR 52](https://github.com/F1LT3R/markserv/pull/52)
1. Simplfy Markserv Base URL
1. Add Headers, Cache and Charset
1. ~~Add error page~~ [PR 52](https://github.com/F1LT3R/markserv/pull/52)
1. ~~Try/Catch failed directory indexes~~ [PR 52](https://github.com/F1LT3R/markserv/pull/52)
	- [ ] Need to add test (`chmod 333 ./unreadable-dir/`)
1. LiveReload only used when port above 0 is provided

Thanks again for your great work @ChenYingChou

**Pull request closed without merging**
