### PR TITLE
Add missing CLI help file

### LINKED ISSUE #78: CLI help text broken
When running `markserv`, I immediately encounter this error:

```
 % markserv --version                                                                                                                                                                                                                                                                :(
fs.js:115
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/Users/liamdawson/.nodenv/versions/10.15.0/lib/node_modules/markserv/lib/cli-help.txt'
    at Object.openSync (fs.js:439:3)
    at Object.readFileSync (fs.js:344:35)
    at Object.<anonymous> (/Users/liamdawson/.nodenv/versions/10.15.0/lib/node_modules/markserv/lib/cli.js:11:27)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```

As the error suggests, no file exists at that location.

### PR DESCRIPTION
**Pull request by liamdawson**
This change is intended to fix #78.

### CODE REVIEW

**Comment by liamdawson** [comment]
By manually downloading these two files into the package folder, I can now get help text and run the app. I presume adding them to the `files` array will ensure they get there.

**Comment by EstebanMarin** [comment]
Why is there in the `readme.js` 2 reference to two files, `cli-defs` and `cli-help.txt`, and not packed in the code. I actually found it here https://github.com/markserv/markserv/blob/master/lib/cli-defs.js
https://github.com/markserv/markserv/blob/master/lib/cli-help.txt

**Comment by F1LT3R** [comment]
Thanks for spotting this. I'll fix tonight.

**Comment by F1LT3R** [comment]
Unless you want to fix now and PR?

**Comment by EstebanMarin** [comment]
Cool, let me do the PR.

**Comment by EstebanMarin** [comment]
I can do the PR. Cool

**Comment by EstebanMarin** [comment]
This PR should fix the issue https://github.com/markserv/markserv/pull/81
of issue https://github.com/markserv/markserv/pull/78
Also the package needs to be re-published as right now is breaking

**Pull request merged**
